### ISSUE TITLE
Configuration files to /etc

### ISSUE THREAD

**Issue by p1839251** [glitsj16/firejail-handler-http#4]
Could you please move the configuration files to `/etc`?
I understand it's a bash script but I wouldn't have to write new patches every time I change the values.
The variables, that can be modified, could be sourced from somewhere else

**Comment by glitsj16** [comment]
> The variables, that can be modified, could be sourced from somewhere else

True. But there's a catch. The configuration file needs to reside in a location that is accessible from inside a firejail sandbox. And, knowing the firejail profiles, even /etc isn't guaranteed to meet that condition. That was exactly the reason why I decided to divert from the usual file layout in the PKGBUILD. I didn't want to use /etc for the settings. I'll definately consider a better location for `firejail-handler-settings-http.inc`. Or I could support a config in the drop dir location under ${HOME} which has to meet the exact same condition and wouldn't be touched by installing/upgrading the package. Stay tuned...

Thanks for reporting
